- name: add ssh key for lulu
  authorized_key:
    user: lulu
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFcZEhBA0mWMUUC56MrWQm7BW9HrKnBEDbtJM1BoQNo+ ansible"


- name: generate sshd_config file from template
  tags: ssh
  template:
    src: "{{ ssh_template_file }}"
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
  notify: restart_sshd    
